#include "src/apps/hstream-ui/ApplicationIdentity.h"

#include <QtCore/QBuffer>
#include <QtCore/QCoreApplication>
#include <QtCore/QDir>
#include <QtCore/QFile>
#include <QtCore/QFileInfo>
#include <QtCore/QSaveFile>
#include <QtCore/QStandardPaths>
#include <QtGui/QGuiApplication>
#include <QtGui/QPainter>
#include <QtGui/QPainterPath>

namespace hm::ui_internal {
namespace {

constexpr auto kManagedLauncher = "# Generated by HStream for an uninstalled command-line build.\n";

QByteArray read_file(const QString& path) {
  QFile file(path);
  return file.open(QIODevice::ReadOnly) ? file.readAll() : QByteArray{};
}

QString save_if_changed(const QString& path, const QByteArray& contents) {
  if (read_file(path) == contents)
    return {};
  if (!QDir().mkpath(QFileInfo(path).absolutePath()))
    return "could not create desktop integration directory for " + path;
  QSaveFile file(path);
  if (!file.open(QIODevice::WriteOnly) || file.write(contents) != contents.size() || !file.commit())
    return "could not save " + path + ": " + file.errorString();
  return {};
}

QString desktop_string(QString value) {
  value.replace('\\', "\\\\");
  value.replace('\n', "\\n");
  value.replace('\r', "\\r");
  value.replace('\t', "\\t");
  return value;
}

QString desktop_command(QString path) {
  // Desktop Entry string escaping is applied before Exec argument unquoting.
  // GIO checks the executable before expanding %% field codes. Use env for
  // literal-percent paths so the actual program is expanded as an argument.
  const QString prefix = path.contains('%') ? "/usr/bin/env -- " : "";
  path.replace('\\', "\\\\");
  path.replace('"', "\\\"");
  path.replace('$', "\\$");
  path.replace('`', "\\`");
  path.replace('%', "%%");
  return prefix + desktop_string('"' + path + '"');
}

} // namespace

void configure_application_identity() {
  QCoreApplication::setApplicationName("hstream-ui");
  QGuiApplication::setApplicationDisplayName("HStream");
  QGuiApplication::setDesktopFileName("hstream-ui");
}

QIcon application_icon() {
  // Keep this vector drawing in sync with hstream-ui.svg, used by installers.
  // Drawing directly avoids a runtime dependency on the Qt SVG image plugin.
  static const QIcon icon = [] {
    QIcon result;
    for (const int size : {16, 24, 32, 48, 64, 128, 256, 512}) {
      QPixmap pixmap(size, size);
      pixmap.fill(Qt::transparent);
      QPainter painter(&pixmap);
      painter.setRenderHint(QPainter::Antialiasing);
      painter.scale(size / 512.0, size / 512.0);
      QLinearGradient background(64, 42, 448, 470);
      background.setColorAt(0.0, QColor("#071523"));
      background.setColorAt(0.55, QColor("#0a3552"));
      background.setColorAt(1.0, QColor("#08718a"));
      painter.setPen(Qt::NoPen);
      painter.setBrush(background);
      painter.drawRoundedRect(QRectF(18, 18, 476, 476), 108, 108);

      painter.setBrush(Qt::NoBrush);
      painter.setPen(QPen(QColor(66, 225, 239, 89), 16));
      painter.drawRoundedRect(QRectF(81, 155, 350, 202), 99, 99);
      painter.setPen(QPen(QColor("#f7fbff"), 34, Qt::SolidLine, Qt::RoundCap));
      painter.drawLine(QPointF(340, 106), QPointF(217, 335));
      QPainterPath blade;
      blade.moveTo(217, 335);
      blade.quadTo(210, 348, 195, 348);
      blade.lineTo(108, 348);
      painter.setPen(QPen(QColor("#f7fbff"), 48, Qt::SolidLine, Qt::RoundCap, Qt::RoundJoin));
      painter.drawPath(blade);
      painter.setPen(QPen(QColor("#0a3552"), 9, Qt::SolidLine, Qt::FlatCap));
      painter.drawLine(QPointF(312, 132), QPointF(342, 148));
      painter.drawLine(QPointF(302, 152), QPointF(332, 168));

      QPainterPath puck;
      puck.moveTo(303, 350);
      puck.lineTo(303, 373);
      puck.cubicTo(303, 384.046, 324.938, 393, 352, 393);
      puck.cubicTo(379.062, 393, 401, 384.046, 401, 373);
      puck.lineTo(401, 350);
      painter.setPen(QPen(QColor("#42e1ef"), 8));
      painter.setBrush(QColor("#05131e"));
      painter.drawPath(puck);
      painter.setPen(QPen(QColor("#8ff8ff"), 8));
      painter.setBrush(QColor("#142f43"));
      painter.drawEllipse(QPointF(352, 350), 49, 20);
      QPainterPath highlight;
      highlight.moveTo(329, 347);
      highlight.quadTo(352, 337, 375, 347);
      painter.setBrush(Qt::NoBrush);
      painter.setPen(QPen(QColor("#42e1ef"), 6, Qt::SolidLine, Qt::RoundCap));
      painter.drawPath(highlight);
      painter.setPen(QPen(QColor("#f7fbff"), 8));
      painter.setBrush(QColor("#ff4f64"));
      painter.drawEllipse(QPointF(119, 111), 25, 25);
      painter.end();
      result.addPixmap(pixmap);
    }
    return result;
  }();
  return icon;
}

QString ensure_desktop_integration(const QString& executable_path) {
#if defined(Q_OS_LINUX)
  const QString data_home = QStandardPaths::writableLocation(QStandardPaths::GenericDataLocation);
  if (data_home.isEmpty())
    return "no user data directory is available for desktop integration";
  const QString launcher = QDir(data_home).filePath("applications/hstream-ui.desktop");
  const QFileInfo existing_launcher(launcher);
  const bool managed = !existing_launcher.isSymLink() && read_file(launcher).startsWith(kManagedLauncher);
  if ((existing_launcher.exists() || existing_launcher.isSymLink()) && !managed)
    return {}; // Preserve custom launchers, including explicit Hidden=true overrides.

  for (const QString& data_directory : QStandardPaths::standardLocations(QStandardPaths::GenericDataLocation)) {
    const QString candidate = QDir(data_directory).filePath("applications/hstream-ui.desktop");
    if (QDir::cleanPath(candidate) != QDir::cleanPath(launcher) && QFileInfo::exists(candidate)) {
      // A later package installation supersedes our development fallback.
      if (managed && !QFile::remove(launcher))
        return "could not retire the development desktop entry " + launcher;
      return {};
    }
  }

  const QString icon_path = QDir(data_home).filePath("hstream-ui/hstream-ui.png");
  QByteArray png;
  QBuffer buffer(&png);
  if (!buffer.open(QIODevice::WriteOnly) || !application_icon().pixmap(256, 256).save(&buffer, "PNG"))
    return "could not encode the HStream desktop icon";
  const QString icon_error = save_if_changed(icon_path, png);
  if (!icon_error.isEmpty())
    return icon_error;
  const QByteArray entry =
      QString::fromLatin1(kManagedLauncher)
          .append(
              "[Desktop Entry]\nType=Application\nName=HStream\nGenericName=Live Video Production\n"
              "Comment=GPU video stitching and live production control\nExec=%1\nIcon=%2\n"
              "Terminal=false\nCategories=AudioVideo;Video;\nStartupNotify=true\nStartupWMClass=hstream-ui\n")
          .arg(desktop_command(QFileInfo(executable_path).absoluteFilePath()), desktop_string(icon_path))
          .toUtf8();
  return save_if_changed(launcher, entry);
#else
  (void)executable_path;
  return {};
#endif
}

} // namespace hm::ui_internal
