exports_files(["AssetsMain.cpp"])

filegroup(
  name = "runtime_sources",
  srcs = ["AssetsMain.cpp"],
  visibility = ["//visibility:public"],
)

cc_binary(
  name = "hstream-assets",
  srcs = ["AssetsMain.cpp"],
  visibility = ["//visibility:public"],
  deps = ["//src/libs/assets:asset_manager"],
)
