load("@rules_cuda//cuda:defs.bzl", "cuda_library")

INCLUDE_PREFIX = "hstream/src/libs/draw_display"

cc_library(
    name = "draw_display",
    srcs = [
        "DrawDisplayMeta.cpp",
        "Fonts.cpp",
    ],
    hdrs = [
        "DrawDisplayMeta.h",
        "Fonts.h",
        "stb_truetype.h",
    ],
    include_prefix = INCLUDE_PREFIX,
    visibility = ["//visibility:public"],
    deps = [
        "//src/libs/common:utils",
        "@deepstream//sources:deepstream_includes",
        "@com_google_absl//absl/status",
        # ":draw_display_cuda_lib",
    ],
)

cuda_library(
    name = "draw_display_cuda_lib",
    srcs = [
        "cudaDrawText.cu",
    ],
    hdrs = [
    ],
    copts = [
        "-std=c++17",
        "-Xcompiler=-fPIC",
        # "-Xcompiler=-rdynamic",
        #"-Xcompiler=-O0",
        #"-Xcompiler=-g",
        "-Wno-deprecated-gpu-targets",
        #"-G",
        #"-g",
        "-keep",
        #"-O0",
    ],
    # includes = ["."],
    visibility = ["//visibility:private"],
    deps = [
        "//src/libs/common:utils",
        "@local_cuda//:cuda_runtime",
    ],
)
