def _doxygen_impl(ctx):
    out_dir = ctx.actions.declare_directory(ctx.attr.name + "_html")

    # Compose INPUT list from all declared sources
    inputs = ctx.files.srcs
    if ctx.file.mainpage:
        inputs = inputs + [ctx.file.mainpage]
    input_list = " ".join([f.path for f in inputs])

    cfg = ctx.actions.declare_file(ctx.attr.name + "_Doxyfile")
    lines = [
        "PROJECT_NAME = \"%s\"" % ctx.attr.project_name,
        "PROJECT_BRIEF = \"Autogenerated API documentation (Doxygen).\"",
        "OUTPUT_DIRECTORY = %s" % out_dir.path,
        "GENERATE_HTML = YES",
        "HTML_OUTPUT = html",
        "GENERATE_LATEX = NO",
        "FULL_PATH_NAMES = YES",
        # leave STRIP_FROM_PATH unset to avoid path mismatches under sandbox
        "JAVADOC_AUTOBRIEF = YES",
        "MULTILINE_CPP_IS_BRIEF = YES",
        "OPTIMIZE_OUTPUT_FOR_C = NO",
        "OPTIMIZE_OUTPUT_JAVA = NO",
        "OPTIMIZE_FOR_FORTRAN = NO",
        "OPTIMIZE_OUTPUT_VHDL = NO",
        "MARKDOWN_SUPPORT = YES",
        "AUTOLINK_SUPPORT = YES",
        "EXTRACT_ALL = YES",
        "EXTRACT_PRIVATE = NO",
        "EXTRACT_STATIC = YES",
        "SOURCE_BROWSER = YES",
        "INLINE_SOURCES = NO",
        "REFERENCES_RELATION = YES",
        "REFERENCED_BY_RELATION = YES",
        "CALL_GRAPH = NO",
        "CALLER_GRAPH = NO",
        "HAVE_DOT = NO",
        "RECURSIVE = NO",
        # We pass explicit file list rather than directories to satisfy Bazel sandboxing
        "INPUT = %s" % input_list,
        "FILE_PATTERNS = *.h *.hpp *.hh *.c *.cc *.cpp *.cxx *.cu *.cuh",
        "EXTENSION_MAPPING = cu=C++ cuh=C++",
        "GENERATE_TREEVIEW = YES",
        "SORT_BRIEF_DOCS = YES",
        "SORT_BY_SCOPE_NAME = YES",
        "ALPHABETICAL_INDEX = YES",
    ]
    if ctx.file.mainpage:
        lines.append("USE_MDFILE_AS_MAINPAGE = %s" % ctx.file.mainpage.path)
    cfg_content = "\n".join(lines)
    ctx.actions.write(cfg, cfg_content)

    # Run doxygen
    ctx.actions.run(
        inputs = inputs + [cfg],
        outputs = [out_dir],
        arguments = [cfg.path],
        executable = ctx.executable.doxygen,
        progress_message = "Generating Doxygen docs: %s" % ctx.attr.project_name,
        mnemonic = "DoxygenDocs",
    )

    return [DefaultInfo(files = depset([out_dir]))]


doxygen_docs = rule(
    implementation = _doxygen_impl,
    attrs = {
        "srcs": attr.label_list(allow_files = True),
        "project_name": attr.string(default = "hstream"),
        "doxygen": attr.label(executable = True, cfg = "exec", allow_files = True),
        "mainpage": attr.label(allow_single_file = True),
    },
)
