INCLUDE_PREFIX = "hstream/libs/stitching"

cc_library(
  name = "stitching",
  srcs = glob([
    "*.cpp",
  ]),
  hdrs = glob([
    "*.h",
  ]),
  include_prefix = INCLUDE_PREFIX,
  visibility = ["//visibility:public"],
  deps = [
    "//src/libs/common:utils",
    "@com_google_absl//absl/status:status",
  ],
)
