exports_files([
    ".bazelrc",
    "run.sh",
])

config_setting(
    name = "use_hip",
    values = {"define": "backend=hip"},
)

config_setting(
    name = "use_vulkan",
    values = {"define": "backend=vulkan"},
)

filegroup(
    name = "all_source",
    srcs = glob([
        "src/**/*.h",
        "src/**/*.hh",
        "src/**/*.hpp",
        "src/**/*.c",
        "src/**/*.cc",
        "src/**/*.cpp",
        "src/**/*.cxx",
        "src/**/*.cu",
        "src/**/*.cuh",
    ], exclude=[
        "src/**/third_party/**",
        "src/**/external/**",
    ]),
    visibility = ["//visibility:public"],
)
