#!/bin/bash

HOST_ARCH="$(uname -m)"
BAZEL_FLAGS="--config=opt"
IS_JETSON=0
if [ -e /etc/nv_tegra_release ]; then
  IS_JETSON=1
elif [ -r /proc/device-tree/compatible ] && tr '\0' '\n' < /proc/device-tree/compatible | grep -qi tegra; then
  IS_JETSON=1
fi
if [ "${HOST_ARCH}" = "x86_64" ]; then
  BAZEL_FLAGS="${BAZEL_FLAGS} --cpu=k8"
fi
if [ "${HOST_ARCH}" = "aarch64" ] && [ "${IS_JETSON}" = "0" ]; then
  BAZEL_FLAGS="${BAZEL_FLAGS} --config=arm64"
fi

bazelisk build ${BAZEL_FLAGS} //...
