_workspace_name = "kstream"

workspace(name = _workspace_name)

load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository", "new_git_repository")
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
load("//bazel:conditional_local_repository.bzl", "conditional_local_repository")

local_repository(
    name = "gst_plugin_dev",
    path = ".",
)

local_repository(
    name = "rules_compdb",
    path = "/home/colivier/src/hstream/bazel",
)

git_repository(
    name = "rules_cuda",
    # v0.2.3 breaks some lubcupti for our version of bazel
    commit = "3f2429254ec956220557e79ea9d5f5e8871c2907",
    remote = "https://github.com/bazel-contrib/rules_cuda",
)

load("@rules_cuda//cuda:repositories.bzl", "register_detected_cuda_toolchains", "rules_cuda_dependencies")

rules_cuda_dependencies()

register_detected_cuda_toolchains()

register_toolchains("//toolchains/jetson:jetson_toolchain")

conditional_local_repository(
    name = "deepstream",
    build_file = "@//buildfiles:third_party/deepstream.BUILD",
    paths = [
        "/opt/jetson-sysroot/opt/nvidia/deepstream/deepstream",
        "/opt/nvidia/deepstream/deepstream",
    ],
)

conditional_local_repository(
    name = "misc",
    build_file = "//buildfiles:third_party/misc.BUILD",
    paths = [
        "/opt/jetson-sysroot/usr/include",
        "/usr/include",
    ],
)

new_local_repository(
    name = "glibconfig_x86",
    build_file = "//buildfiles:third_party/glibconfig.BUILD",
    path = "/usr/lib/x86_64-linux-gnu/glib-2.0/include",
)

conditional_local_repository(
    name = "glibconfig_aarch64",
    build_file = "//buildfiles:third_party/glibconfig.BUILD",
    paths = [
        "/opt/jetson-sysroot/usr/lib/aarch64-linux-gnu/glib-2.0/include",
        "/usr/lib/x86_64-linux-gnu/glib-2.0/include",
    ],
)

new_git_repository(
    name = "yaml-cpp",
    build_file = "@//buildfiles:third_party/yaml-cpp.BUILD",
    commit = "f7320141120f720aecc4c32be25586e7da9eb978",
    remote = "https://github.com/jbeder/yaml-cpp.git",
)

http_archive(
    name = "rules_python",
    sha256 = "9c6e26911a79fbf510a8f06d8eedb40f412023cf7fa6d1461def27116bff022c",
    strip_prefix = "rules_python-1.1.0",
    url = "https://github.com/bazelbuild/rules_python/releases/download/1.1.0/rules_python-1.1.0.tar.gz",
)

# {fmt} for SimpleDBus logging
http_archive(
    name = "com_github_fmtlib_fmt",
    urls = [
        "https://github.com/fmtlib/fmt/archive/refs/tags/11.0.2.tar.gz",
    ],
    strip_prefix = "fmt-11.0.2",
    sha256 = "6cb1e6d37bdcb756dbbe59be438790db409cdb4868c66e888d5df9f13f7c027f",
    build_file = "@//buildfiles:third_party/fmt.BUILD",
)

load("@rules_python//python:repositories.bzl", "py_repositories")

py_repositories()

git_repository(
    name = "magic_enum",
    remote = "https://github.com/Neargye/magic_enum.git",
    strip_prefix = "",  # No need for strip_prefix since Git directly clones the repository
    tag = "v0.9.3",  # Use the tag corresponding to version 0.9.3
)

################################ HockeyMOM Sub-Modules ################################
git_repository(
    name = "hm-cupano",
    commit = "0f7934a7137ee5adcd7c5844fe786e8e6f6dfa6b",
    remote = "ssh://git@github.com/cjolivier01/hm-cupano",
)

git_repository(
    name = "jetson-utils",
    commit = "f4b85fbd89262e60deba1ab580d421f9614e8ca6",
    remote = "ssh://git@github.com/cjolivier01/jetson-utils",
)

git_repository(
    name = "hm",
    commit = "b9f54ff8c8a9f88ea275a9a924c77498c83b7c89",
    remote = "ssh://git@github.com/cjolivier01/hockeymom2",
)

################################ Multiblend ################################
git_repository(
    name = "multiblend",
    commit = "4fe978fbd6b89a61dbcc290e22e656e5ed0cefd8",
    remote = "ssh://git@github.com/cjolivier01/multiblend",
)

################################ Other Modules ################################

# Abseil Library
git_repository(
    name = "com_google_absl",
    remote = "https://github.com/abseil/abseil-cpp.git",
    # tag = "20250127.0",
    commit = "9ac7062b1860d895fb5a8cbf58c3e9ef8f674b5f",
)

conditional_local_repository(
    name = "glib",
    build_file = "//buildfiles:third_party/glib_nobuild.BUILD",
    paths = [
        "/opt/jetson-sysroot/usr",
        "/usr",
    ],
)

load("//bazel:opencv_configure.bzl", "opencv_configure")

opencv_configure(
    name = "opencv_linux",
)

conditional_local_repository(
    name = "json_glib",
    build_file = "@//buildfiles:third_party/json_glib.BUILD",
    paths = [
        "/opt/jetson-sysroot/usr",
        "/usr",
    ],
)

conditional_local_repository(
    name = "gtk3",
    build_file = "@//buildfiles:third_party/gtk3.BUILD",
    paths = [
        "/opt/jetson-sysroot/usr/include/gtk-3.0",
        "/usr/include/gtk-3.0",
    ],
)

conditional_local_repository(
    name = "cairo",
    build_file = "@//buildfiles:third_party/gtk3.BUILD",
    paths = [
        "/opt/jetson-sysroot/usr/include/cairo",
        "/usr/include/cairo",
    ],
)

conditional_local_repository(
    name = "gdk-pixbuf",
    build_file = "@//buildfiles:third_party/gtk3.BUILD",
    paths = [
        "/opt/jetson-sysroot/usr/include/gdk-pixbuf-2.0",
        "/usr/include/gdk-pixbuf-2.0",
    ],
)

conditional_local_repository(
    name = "harfbuzz",
    build_file = "@//buildfiles:third_party/gtk3.BUILD",
    paths = [
        "/opt/jetson-sysroot/usr/include/harfbuzz",
        "/usr/include/harfbuzz",
    ],
)

conditional_local_repository(
    name = "pango",
    build_file = "@//buildfiles:third_party/gtk3.BUILD",
    paths = [
        "/opt/jetson-sysroot/usr/include/pango-1.0",
        "/usr/include/pango-1.0",
    ],
)

conditional_local_repository(
    name = "atk",
    build_file = "@//buildfiles:third_party/gtk3.BUILD",
    paths = [
        "/opt/jetson-sysroot/usr/include/atk-1.0",
        "/usr/include/atk-1.0",
    ],
)


conditional_local_repository(
    name = "gstreamer",
    build_file = "@//buildfiles:third_party/gstreamer_nobuild.BUILD",
    paths = [
        "/opt/jetson-sysroot/usr",
        "/usr",
    ],
)

conditional_local_repository(
    name = "libsoup",
    build_file = "@//buildfiles:third_party/libsoup.BUILD",
    paths = [
        "/opt/jetson-sysroot/usr",
        "/usr",
    ],
)

# SimpleBLE (and subprojects SimpleDBus, SimpleBluez)
# We vendor it as a git_repository and provide our own Bazel BUILD file.
# Note: Using branch for convenience; consider pinning a tag/commit for reproducibility.
git_repository(
    name = "simpleble",
    remote = "https://github.com/simpleble/simpleble.git",
    commit = "b342bc93894d520ff5885fa5f45fc650bba11d79",
    build_file = "@//buildfiles:third_party/simpleble.BUILD.bazel",
)

# System headers for DBus and BlueZ as local repositories
conditional_local_repository(
    name = "dbus",
    build_file = "@//buildfiles:third_party/dbus.BUILD",
    paths = [
        "/opt/jetson-sysroot/usr",
        "/usr",
    ],
)

conditional_local_repository(
    name = "bluez",
    build_file = "@//buildfiles:third_party/bluez.BUILD",
    paths = [
        "/opt/jetson-sysroot/usr",
        "/usr",
    ],
)
