load("@rules_cuda//cuda:defs.bzl", "cuda_library")

INCLUDE_PREFIX = "hstream/src/gst-plugins/gst-videoprep/playcropper"

cc_library(
    name = "playcropper",
    srcs = [
      "playcropper.cpp",
    ],
    hdrs = [
      "playcropper.h",
    ],
    include_prefix = INCLUDE_PREFIX,
    visibility = ["//visibility:public"],
    deps = [
        ":play_cropper_cuda_lib",
        "//src/gst-plugins/gst-videoprep/algorithm-base",
        "//src/gst-plugins/gst-playtracker:playtracker_context_header",
        "//src/gst-plugins/gst-videoprep/playtracker:playtracker_payload",
        "//src/libs/common:preview_overlay_meta",
        "//src/libs/common:utils",
        "//src/libs/draw_display",
        "//src/libs/scoreboard",
        "//src/libs/stitching",
        "@hm-cupano//src/pano:cuda_matrix",
        "@yaml-cpp",
    ],
)

cc_test(
    name = "playcropper_runtime_sizing_test",
    srcs = ["PlayCropperRuntimeSizingTest.cpp"],
    deps = [
        ":playcropper",
        "@deepstream//:deepstream_lib",
        "@gstreamer",
        "@local_cuda//:nppc",
        "@local_cuda//:nppif",
        "@local_cuda//:nppig",
        "//toolchains/jetson:cuda_runtime",
    ],
    copts = [
        "-x",
        "c++",
        "-std=c++17",
    ],
    linkopts = [
        "-lnvdsbufferpool",
    ],
)

cc_test(
    name = "playcropper_metadata_alignment_test",
    srcs = ["PlayCropperMetadataAlignmentTest.cpp"],
    deps = [
        "//src/gst-plugins/gst-playtracker:playtracker_context_header",
        "//src/gst-plugins/gst-videoprep/algorithm-base",
        "@deepstream//:deepstream_lib",
        "@gstreamer",
        "@local_cuda//:nppc",
        "@local_cuda//:nppif",
        "@local_cuda//:nppig",
        "//toolchains/jetson:cuda_runtime",
    ],
    copts = [
        "-x",
        "c++",
        "-std=c++17",
    ],
    linkopts = [
        "-lnvdsbufferpool",
    ],
)

cc_test(
    name = "shadow_tone_curve_test",
    srcs = ["ShadowToneCurveTest.cpp"],
    deps = [":shadow_tone_curve"],
)

cc_test(
    name = "shadow_tone_cuda_test",
    srcs = ["ShadowToneCudaTest.cpp"],
    deps = [
        ":play_cropper_cuda_lib",
        ":play_cropper_cuda_lib_h",
        ":shadow_tone_curve",
        "@deepstream//:deepstream_lib",
        "//toolchains/jetson:cuda_runtime",
    ],
)

cc_library(
    name = "shadow_tone_curve",
    hdrs = ["ShadowToneCurve.h"],
    include_prefix = INCLUDE_PREFIX,
    visibility = ["//visibility:public"],
)

cuda_library(
    name = "play_cropper_cuda_lib",
    srcs = [
        "cudaPlayCropper.cu",
    ],
    hdrs = [
    ],
    copts = [
        # "-std=c++17",
        "-Xcompiler=-fPIC",
        # "-Xcompiler=-rdynamic",
        #"-Xcompiler=-O0",
        #"-Xcompiler=-g",
        "-Wno-deprecated-gpu-targets",
        #"-G",
        #"-g",
        "-keep",
        #"-O0",
    ],
    # includes = ["."],
    visibility = ["//visibility:private"],
    deps = [
        ":play_cropper_cuda_lib_h",
        ":shadow_tone_curve",
        "//src/libs/common:utils",
        "@deepstream//:deepstream_lib",
        "//toolchains/jetson:cuda_runtime",
    ],
)

cc_library(
    name = "play_cropper_cuda_lib_h",
    srcs = [
    ],
    hdrs = [
        "cudaPlayCropper.h",
    ],
    include_prefix = INCLUDE_PREFIX,
    visibility = ["//visibility:public"],
    deps = [
        "//src/libs/common:utils",
        "@deepstream//:deepstream_lib",
        "//toolchains/jetson:cuda_runtime",
    ],
)
