load("@gst_plugin_dev//build:gst_plugin.bzl", "gst_cc_plugin")

gst_cc_plugin(
    name = "nvdsgst_audio_filter",
    srcs = glob(["*.cpp"]),
    hdrs = glob(["*.h"]),
    copts = [
    ],
    visibility = ["//visibility:public"],
    deps = [],
)
