load("@rules_cc//cc:defs.bzl", "cc_binary")

cc_binary(
    name = "gopro_ble",
    srcs = [
        "GoProBle.cpp",
    ],
    copts = [
        "-std=c++17",
        "-DHSTREAM_HAVE_SIMPLEBLE",
    ],
    deps = [
        "@simpleble//:simpleble",
    ],
    visibility = ["//visibility:public"],
)
