cc_binary(
    name = "int8-calib-builder",
    srcs = ["int8_calib_builder.cpp", "EnginePrecision.h"],
    copts = [
        "-Wall",
        "-std=c++17",
        "-Wno-error=deprecated-declarations",
    ],
    linkopts = [
        "-Wno-error=deprecated-declarations",
        "-Wl,--start-group",
        "-L/usr/local/cuda/lib64",
        "-lcudart",
        "-Wl,--end-group",
    ],
    deps = [
        "@detector_tensorrt//:sdk",
        "@local_cuda//:cuda",
        "@opencv_linux//:opencv",
        "@yaml-cpp",
        "//toolchains/jetson:cuda_runtime",
    ],
)

cc_test(
    name = "engine_precision_test",
    srcs = ["EnginePrecisionTest.cpp", "EnginePrecision.h"],
    deps = ["@yaml-cpp"],
)
