INCLUDE_PREFIX = "hstream/src/apps/apps-common"

cc_library(
    name = "gst_plugin_properties",
    srcs = ["gst_plugin_properties.cpp"],
    hdrs = ["gst_plugin_properties.h"],
    copts = [
        "-x",
        "c++",
        "-std=c++17",
    ],
    include_prefix = INCLUDE_PREFIX,
    visibility = ["//visibility:public"],
    deps = [
        "@glib",
        "@gstreamer",
        "@yaml-cpp",
    ],
)

cc_library(
    name = "deepstream_apps_common",
    srcs = [
        "deepstream-yaml/deepstream_config_yaml.cpp",
        "deepstream-yaml/deepstream_dewarper_yaml.cpp",
        "deepstream-yaml/deepstream_dsanalytics_yaml.cpp",
        "deepstream-yaml/deepstream_dsexample_yaml.cpp",
        "deepstream-yaml/deepstream_gie_yaml.cpp",
        "deepstream-yaml/deepstream_image_save_yaml.cpp",
        "deepstream-yaml/deepstream_msgconsumer_yaml.cpp",
        "deepstream-yaml/deepstream_msgconv_yaml.cpp",
        "deepstream-yaml/deepstream_osd_yaml.cpp",
        "deepstream-yaml/deepstream_preprocess_yaml.cpp",
        "deepstream-yaml/deepstream_segvisual_yaml.cpp",
        "deepstream-yaml/deepstream_sink_yaml.cpp",
        "deepstream-yaml/deepstream_source_yaml.cpp",
        "deepstream-yaml/deepstream_streammux_yaml.cpp",
        "deepstream-yaml/deepstream_tiled_display_yaml.cpp",
        "deepstream-yaml/deepstream_tracker_yaml.cpp",
        "deepstream_audio_classifier_bin.cpp",
        "deepstream_c2d_msg.cpp",
        "deepstream_c2d_msg_util.cpp",
        "deepstream_common.cpp",
        "deepstream_config_file_parser.cpp",
        "deepstream_dewarper_bin.cpp",
        "deepstream_dsanalytics.cpp",
        "deepstream_dsexample.cpp",
        "deepstream_dsfieldmask.cpp",
        "deepstream_osd_bin.cpp",
        "deepstream_perf.cpp",
        "deepstream_preprocess.cpp",
        "deepstream_primary_gie_bin.cpp",
        "deepstream_secondary_gie_bin.cpp",
        "deepstream_secondary_preprocess.cpp",
        "deepstream_segvisual_bin.cpp",
        "deepstream_sink_bin.cpp",
        "deepstream_source_bin.cpp",
        "deepstream_streammux.cpp",
        "deepstream_tiled_display_bin.cpp",
        "deepstream_tracker_bin.cpp",
    ],
    hdrs = [
        "deepstream_app_version.h",
        "deepstream_audio_classifier.h",
        "deepstream_c2d_msg.h",
        "deepstream_c2d_msg_util.h",
        "deepstream_common.h",
        "deepstream_config.h",
        "deepstream_config_file_parser.h",
        "deepstream_config_yaml.h",
        "deepstream_dewarper.h",
        "deepstream_dsanalytics.h",
        "deepstream_dsexample.h",
        "deepstream_dsfieldmask.h",
        "deepstream_gie.h",
        "deepstream_image_save.h",
        "deepstream_osd.h",
        "deepstream_perf.h",
        "deepstream_preprocess.h",
        "deepstream_primary_gie.h",
        "deepstream_secondary_gie.h",
        "deepstream_secondary_preprocess.h",
        "deepstream_segvisual.h",
        "deepstream_sinks.h",
        "deepstream_sources.h",
        "deepstream_streammux.h",
        "deepstream_tiled_display.h",
        "deepstream_tracker.h",
        "gst_plugin_properties.h",
    ],
    copts = [
        "-x",
        "c++",
        "-std=c++17",
        "-DGST_USE_UNSTABLE_API",
        "-Wno-error=write-strings",
    ],
    include_prefix = INCLUDE_PREFIX,
    includes = [
        ".",
    ],
    visibility = ["//visibility:public"],
    deps = [
        ":gst_plugin_properties",
        "//src/libs/camera",
        "//src/libs/common:fs",
        "//src/libs/common:utils",
        "//toolchains/jetson:cuda_runtime",
        "@deepstream//:deepstream_lib",
        "@glib",
        "@gstreamer",
        "@json_glib",
        "@libsoup",
    ],
)

cc_binary(
    name = "uri_playlist_switch_test",
    srcs = ["UriPlaylistSwitchTest.cpp"],
    deps = [
        ":deepstream_apps_common",
    ],
)

cc_test(
    name = "uri_multiple_pipeline_test",
    srcs = ["UriMultiplePipelineTest.cpp"],
    size = "medium",
    tags = [
        "local",
        "no-cache",
    ],
    timeout = "moderate",
    deps = [
        ":deepstream_apps_common",
        "@gstreamer",
    ],
)

cc_test(
    name = "gst_plugin_properties_test",
    srcs = ["GstPluginPropertiesTest.cpp"],
    deps = [
        ":gst_plugin_properties",
        "@gstreamer",
        "@yaml-cpp",
    ],
)
