cc_library(
    name = "playtracker_replay",
    srcs = ["ReplaySession.cpp"],
    hdrs = ["ReplaySession.h"],
    include_prefix = "hstream/src/libs/playtracker_replay",
    visibility = ["//visibility:public"],
    deps = [
        "//src/libs/recording",
        "//src/gst-plugins/gst-playtracker:playtracker_context",
        "//src/gst-plugins/gst-playtracker:playtracker_runtime_config",
        "@com_google_absl//absl/status:statusor",
        "@hm//hockeymon/csrc/play_tracker",
        "@yaml-cpp",
    ],
)

cc_test(
    name = "playtracker_replay_test",
    srcs = ["ReplaySessionTest.cpp"],
    deps = [
        ":playtracker_replay",
        "@opencv_linux//:opencv",
        "//src/libs/recording",
        "//src/gst-plugins/gst-videoprep/playtracker:playtracker_telemetry_db",
        "//src/gst-plugins/gst-videoprep/playtracker:playtracker_telemetry_csv",
        "//src/gst-plugins/gst-playtracker:playtracker_context",
        "@yaml-cpp",
    ],
)
