/*
 * SPDX-FileCopyrightText: Copyright (c) 2020-2021 NVIDIA CORPORATION &
 * AFFILIATES. All rights reserved. SPDX-License-Identifier:
 * LicenseRef-NvidiaProprietary
 *
 * NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
 * property and proprietary rights in and to this material, related
 * documentation and any modifications thereto. Any use, reproduction,
 * disclosure or distribution of this material and related documentation
 * without an express license agreement from NVIDIA CORPORATION or
 * its affiliates is strictly prohibited.
 */

#ifndef __GST_DSPLAYTRACKER_H__
#define __GST_DSPLAYTRACKER_H__

#include <gst/base/gstbasetransform.h>
#include <gst/video/video.h>

#include <cuda.h>
#include <cuda_runtime.h>
#include "PlayTrackerCtx.h"
#include "nvdsmeta.h"
#include "nvbufsurface.h"
#include "nvtx3/nvToolsExt.h"

#include "hockeymom/csrc/play_tracker/PlayTracker.h"

#include <vector>

/* Package and library details required for plugin_init */
#define PACKAGE "playtracker"
#define VERSION "1.0"
#define LICENSE "Proprietary"
#define DESCRIPTION \
  "NVIDIA example plugin for integration with DeepStream on DGPU/Jetson"
#define BINARY_PACKAGE \
  "NVIDIA DeepStream 3rdparty IP integration example plugin"
#define URL "http://nvidia.com/"

G_BEGIN_DECLS
/* Standard boilerplate stuff */
typedef struct _GstDsPlayTracker GstDsPlayTracker;
typedef struct _GstDsPlayTrackerClass GstDsPlayTrackerClass;

/* Standard boilerplate stuff */
#define GST_TYPE_DSPLAYTRACKER (gst_playtracker_get_type())
#define GST_DSPLAYTRACKER(obj) \
  (G_TYPE_CHECK_INSTANCE_CAST((obj), GST_TYPE_DSPLAYTRACKER, GstDsPlayTracker))
#define GST_DSPLAYTRACKER_CLASS(klass) \
  (G_TYPE_CHECK_CLASS_CAST((klass), GST_TYPE_DSPLAYTRACKER, GstDsPlayTrackerClass))
#define GST_DSPLAYTRACKER_GET_CLASS(obj) \
  (G_TYPE_INSTANCE_GET_CLASS((obj), GST_TYPE_DSPLAYTRACKER, GstDsPlayTrackerClass))
#define GST_IS_DSPLAYTRACKER(obj) \
  (G_TYPE_CHECK_INSTANCE_TYPE((obj), GST_TYPE_DSPLAYTRACKER))
#define GST_IS_DSPLAYTRACKER_CLASS(klass) \
  (G_TYPE_CHECK_CLASS_TYPE((klass), GST_TYPE_DSPLAYTRACKER))
#define GST_DSPLAYTRACKER_CAST(obj) ((GstDsPlayTracker*)(obj))

/** Maximum batch size to be supported by playtracker. */
#define NVDSPLAYTRACKER_MAX_BATCH_SIZE 1024

struct _GstDsPlayTracker {
  GstBaseTransform base_trans;

  /** Context of the custom algorithm library */
  DsPlayTrackerCtx* playtrackerlib_ctx;

  /** Processing Queue and related synchronization structures. */

  /** Gmutex lock for against shared access in threads**/
  GMutex process_lock;

  /** Queue to send data to output thread for processing**/
  GQueue* process_queue;

  /** Gcondition for process queue**/
  GCond process_cond;

  /**Queue to receive processed data from output thread **/
  GQueue* buf_queue;

  /** Gcondition for buf queue **/
  GCond buf_cond;

  /** Output thread. */
  GThread* process_thread;

  /** Boolean to signal output thread to stop. */
  gboolean stop;

  /** Unique ID of the element. Used to identify metadata
   *  generated by this element. */
  guint unique_id;

  /** Frame number of the current input buffer */
  guint64 frame_num;

  /** Input video info (resolution, color format, framerate, etc) */
  GstVideoInfo video_info;

  /** GPU ID on which we expect to execute the task */
  guint gpu_id;

  /** send play tracking shapes to the OSD (who may or may not drw them) */
  gboolean draw;

  char play_tracker_config_file[PATH_MAX*4];

  /** Current batch number of the input batch. */
  gulong current_batch_num;

  /** GstFlowReturn returned by the latest buffer pad push. */
  GstFlowReturn last_flow_ret;
};

struct GstDsPlayTrackerFrame {
  /** NvDsObjectParams belonging to the object to be classified. */
  NvDsObjectMeta* obj_meta = nullptr;
  NvDsFrameMeta* frame_meta = nullptr;
  /** Index of the frame in the batched input GstBuffer. Not required for
   * classifiers. */
  guint batch_index = 0;
  /** Frame number of the frame from the source. */
  gulong frame_num = 0;

  hm::play_tracker::PlayTrackerResults play_tracker_results;

  /** The buffer structure the object / frame was converted from. */
  NvBufSurfaceParams* input_surf_params = nullptr;
};

/**
 * Holds information about the batch of frames to be inferred.
 */
struct GstDsPlayTrackerBatch {
  /** Vector of frames in the batch. */
  std::vector<GstDsPlayTrackerFrame> frames;
  /** Pointer to the input GstBuffer. */
  GstBuffer* inbuf = nullptr;
  /** Batch number of the input batch. */
  gulong inbuf_batch_num = 0;
  /** Boolean indicating that the output thread should only push the buffer to
   * downstream element. If set to true, a corresponding batch has not been
   * queued at the input of NvDsPlayTrackerContext and hence dequeuing of output is
   * not required. */
  gboolean push_buffer = FALSE;
  /** Boolean marking this batch as an event marker. This is only used for
   * synchronization. The output loop does not process on the batch.
   */
  gboolean event_marker = FALSE;

  NvBufSurface* inter_buf;

  // nvtxRangeId_t nvtx_complete_buf_range = 0;
};

/** Boiler plate stuff */
struct _GstDsPlayTrackerClass {
  GstBaseTransformClass parent_class;
};

GType gst_playtracker_get_type(void);

G_END_DECLS
#endif /* __GST_DSPLAYTRACKER_H__ */
