load("@gst_plugin_dev//buildfiles:gst_plugin.bzl", "gst_cc_plugin")

gst_cc_plugin(
    name = "nvdsgst_dsfieldmask",
    srcs = [
        "dsfieldmask_lib.cpp",
        "gstdsfieldmask.cpp",
    ],
    hdrs = [
        "dsfieldmask_lib.h",
        "gstdsfieldmask.h",
    ],
    copts = [
        "-Wno-error=unused-function",
        "-Wno-error=unused-variable",
    ],
    linkopts = [
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//src/libs/stitching:stitching",
        "@opencv_linux//:opencv",
        "@com_google_absl//absl/status:statusor",
    ],
)
