load("@gst_plugin_dev//buildfiles:gst_plugin.bzl", "gst_cc_plugin")

INCLUDE_PREFIX = "hstream/src/gst-plugins/gst-fieldmask"

cc_library(
    name = "dsfieldmask_lib",
    srcs = [
        "dsfieldmask_lib.cpp",
    ],
    hdrs = [
        "dsfieldmask_lib.h",
    ],
    include_prefix = INCLUDE_PREFIX,
    visibility = ["//visibility:public"],
    deps = [
        ":fieldmask_payload",
        "//src/libs/common:utils",
        "//src/libs/stitching",
        "@com_google_absl//absl/status:statusor",
        "@deepstream//:deepstream_lib",
        "@opencv_linux//:opencv",
    ],
)

gst_cc_plugin(
    name = "nvdsgst_dsfieldmask",
    srcs = [
        "gstdsfieldmask.cpp",
    ],
    hdrs = [
        "gstdsfieldmask.h",
    ],
    copts = [
        "-Wno-error=unused-function",
        "-Wno-error=unused-variable",
    ],
    linkopts = [
    ],
    visibility = ["//visibility:private"],
    deps = [
        ":dsfieldmask_lib",
        ":fieldmask_payload",
    ],
)

cc_library(
    name = "fieldmask_payload",
    hdrs = ["fieldmask_payload.h"],
    include_prefix = INCLUDE_PREFIX,
    visibility = ["//visibility:public"],
    deps = [
        "//src/libs/common:utils",
    ],
)

cc_test(
    name = "dsfieldmask_plugin_test",
    srcs = [
        "GstDsFieldMaskPluginTest.cpp",
    ],
    copts = [
        "-x",
        "c++",
        "-std=c++17",
    ],
    data = [
        ":libnvdsgst_dsfieldmask.so",
    ],
    deps = [
        "//src/gst-plugins/testutils:gst_plugin_test_harness",
        "@gstreamer",
    ],
)

cc_test(
    name = "dsfieldmask_noop_test",
    srcs = [
        "DsFieldMaskNoopTest.cpp",
    ],
    copts = [
        "-x",
        "c++",
        "-std=c++17",
    ],
    linkopts = [
    ],
    deps = [
        ":dsfieldmask_lib",
    ],
)

cc_test(
    name = "dsfieldmask_load_existing_mask_test",
    srcs = [
        "DsFieldMaskLoadExistingMaskTest.cpp",
    ],
    copts = [
        "-x",
        "c++",
        "-std=c++17",
    ],
    linkopts = [
    ],
    deps = [
        ":dsfieldmask_lib",
        "//src/libs/stitching",
    ],
)
