#ifndef __GST_DSFIELDMASK_H__
#define __GST_DSFIELDMASK_H__

#include <gst/base/gstbasetransform.h>
#include <gst/gst.h>
#include <gst/video/video.h>

/* Open CV headers */
#pragma GCC diagnostic push
#if __GNUC__ >= 8
#pragma GCC diagnostic ignored "-Wclass-memaccess"
#endif
#include "opencv2/highgui/highgui.hpp"
#include "opencv2/imgproc/imgproc.hpp"
#pragma GCC diagnostic pop

#include <cuda.h>
#include <cuda_runtime.h>
#include "dsfieldmask_lib.h"

/* Package and library details required for plugin_init */
#define PACKAGE "dsfieldmask"
#define VERSION "1.0"
#define LICENSE "Proprietary"
#define DESCRIPTION \
  "NVIDIA example plugin for integration with DeepStream on DGPU"
#define BINARY_PACKAGE \
  "NVIDIA DeepStream 3rdparty IP integration example plugin"
#define URL "http://nvidia.com/"

G_BEGIN_DECLS
/* Standard boilerplate stuff */
typedef struct _GstDsFieldMask GstDsFieldMask;
typedef struct _GstDsFieldMaskClass GstDsFieldMaskClass;

/* Standard boilerplate stuff */
#define GST_TYPE_DSFIELDMASK (gst_dsfieldmask_get_type())
#define GST_DSFIELDMASK(obj) \
  (G_TYPE_CHECK_INSTANCE_CAST((obj), GST_TYPE_DSFIELDMASK, GstDsFieldMask))
#define GST_DSFIELDMASK_CLASS(klass) \
  (G_TYPE_CHECK_CLASS_CAST((klass), GST_TYPE_DSFIELDMASK, GstDsFieldMaskClass))
#define GST_DSFIELDMASK_GET_CLASS(obj) \
  (G_TYPE_INSTANCE_GET_CLASS((obj), GST_TYPE_DSFIELDMASK, GstDsFieldMaskClass))
#define GST_IS_DSFIELDMASK(obj) \
  (G_TYPE_CHECK_INSTANCE_TYPE((obj), GST_TYPE_DSFIELDMASK))
#define GST_IS_DSFIELDMASK_CLASS(klass) \
  (G_TYPE_CHECK_CLASS_TYPE((klass), GST_TYPE_DSFIELDMASK))
#define GST_DSFIELDMASK_CAST(obj) ((GstDsFieldMask*)(obj))

/** Maximum batch size to be supported by dsfieldmask. */
// #define NVDSFIELDMASK_MAX_BATCH_SIZE 1024

struct _GstDsFieldMask {
  _GstDsFieldMask() {
    usleep(0);
  }
  GstBaseTransform base_trans;

  // Context of the custom algorithm library
  DsFieldMaskCtx* dsfieldmasklib_ctx;

  // Unique ID of the element. The labels generated by the element will be
  // updated at index `unique_id` of attr_info array in NvDsObjectParams.
  guint unique_id;

  // Frame number of the current input buffer
  guint64 frame_num;

  // Input video info (resolution, color format, framerate, etc)
  GstVideoInfo video_info;

  // Flag which defince igpu/dgpu
  guint is_integrated;

  // GPU ID on which we expect to execute the task
  guint gpu_id;

  gchar detection_mask_file[PATH_MAX * 4];
};

// Boiler plate stuff
struct _GstDsFieldMaskClass {
  GstBaseTransformClass parent_class;
};

GType gst_dsfieldmask_get_type(void);

G_END_DECLS
#endif /* __GST_DSFIELDMASK_H__ */
