exports_files([
    "baseline.yaml",
    "play_tracker_config.yaml",
    "config_infer_yolov8_hockey.yaml",
    "config_infer_yolov8_hockey_bf16.yaml",
    "config_infer_yolov8_hockey_fp16.yaml",
    "config_infer_yolov8_hockey_int8.yaml",
    "config_infer_yolov8s_hockey.yaml",
    "config_infer_yolov8s_hockey_bf16.yaml",
    "config_infer_yolov8s_hockey_fp16.yaml",
    "config_infer_yolov8s_hockey_int8.yaml",
    "ds_hockey_app_config.yaml",
    "ds_hockey_configure_stitching.yaml",
    "stitching_projection_frames.yaml",
    "player-models/pose.json",
    "player-models/jersey.json",
    "player-models/action.json",
    "player-models/reid.json",
])
