# CSI Webcam (Arducam)
source5:
  enable: 1
  # 1: v4l2, 5: CSI
  type: 5
  camera-csi-sensor-id: 1
  camera-i2c-bus: 9

  # Color/Brightness/etc
  camera-wbmode: 5
  camera-exposure-compensation: 0
  camera-saturation: 0.5
  # exposure-time-range: 34000 358733000
  # gain-range: 1 16

  camera-auto-focus: 1
  camera-width: 3840
  camera-height: 2160
  camera-fps-n: 30
  camera-fps-d: 1
  video-format: NV12
  flip-method: 2
  # media-type: image/jpeg
  num-sources: 1
  gpu-id: 0
  input-audio-rate: 189
  source-id: 0
  cuda-memory-type: 1

# CSI Webcam (Arducam)
source6:
  enable: 1
  # 1: v4l2, 5: CSI
  type: 5
  camera-csi-sensor-id: 0
  camera-i2c-bus: 10

  # Color/Brightness/etc
  camera-wbmode: 5
  camera-exposure-compensation: 0
  camera-saturation: 0.5
  # exposure-time-range: 34000 358733000
  # gain-range: 1 16

  camera-auto-focus: 1
  camera-width: 3840
  camera-height: 2160
  camera-fps-n: 30
  camera-fps-d: 1
  video-format: NV12
  flip-method: 2
  num-sources: 1
  gpu-id: 0
  input-audio-rate: 189
  source-id: 1
  cuda-memory-type: 1
