#!/bin/bash
set -e
SCRIPT_DIR=$(dirname $(realpath $0))

BAZEL_FLAGS="--config=debug --cpu=k8"
#BAZEL_FLAGS="--config=opt"

TARGET="$@"
if [ -z "${TARGET}" ]; then
  TARGET="//..."
fi

# echo "USE_BAZEL_VERSION=5.1.1 bazelisk build ${BAZEL_FLAGS} ${TARGET}"
USE_BAZEL_VERSION=5.1.1 bazelisk build ${BAZEL_FLAGS} ${TARGET}

# BIN_DIR="$(bazel info ${BAZEL_FLAGS} bazel-bin)"
# echo "BIN_DIR=${BIN_DIR}"
# EXTENSIONS="$(cat ${SCRIPT_DIR}/extensions.lst)"

# if [ "${TARGET}" == "//..." ]; then
#   for ext in ${EXTENSIONS}; do
#     ln -sf -v ${BIN_DIR}/extensions/${ext}/libgxf_${ext}.so ${SCRIPT_DIR}/_test_libs/libgxf_${ext}.so
#   done
# fi

