_workspace_name = "test"

workspace(name = _workspace_name)

load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository", "new_git_repository")

local_repository(
    name = "com_extension_dev",
    # path = "/home/colivier/src/hmdeepstream/deepstream/graph-composer/extension-dev",
    path = "external/deepstream/graph-composer/extension-dev",
)

local_repository(
    name = "deepstream",
    # path = "/home/colivier/src/hmdeepstream/deepstream",
    path = "external/deepstream",
)

# local_repository(
#   name = "jetson-utils",
#   path = "/home/colivier/src/jetson-utils",
# )

local_repository(
    name = "gst_plugin_dev",
    path = ".",
)

local_repository(
    name = "rules_compdb",
    path = "/home/colivier/src/hstream/bazel",
)

local_repository(
    name = "hm",
    path = "external/hm",
)

load(
    "@com_extension_dev//build:graph_extension.bzl",
    "graph_nvidia_extension",
    "load_extension_dev_workspace",
)

load_extension_dev_workspace()

git_repository(
    name = "rules_cuda",
    # v0.2.3 breaks some lubcupti for our version of bazel
    commit = "3f2429254ec956220557e79ea9d5f5e8871c2907",
    remote = "https://github.com/bazel-contrib/rules_cuda",
)

load("@rules_cuda//cuda:repositories.bzl", "register_detected_cuda_toolchains", "rules_cuda_dependencies")

rules_cuda_dependencies()

register_detected_cuda_toolchains()

graph_nvidia_extension(
    name = "NvDsInterfaceExt",
    version = "1.6.0",
)

graph_nvidia_extension(
    name = "NvDsBaseExt",
    version = "1.6.0",
)

graph_nvidia_extension(
    name = "StandardExtension",
    version = "2.6.0",
)

# new_local_repository(
#     name = "glibconfig",
#     build_file = "//build:third_party/glibconfig.BUILD",
#     path = "/lib/x86_64-linux-gnu/glib-2.0/include",
# )

new_git_repository(
    name = "yaml-cpp",
    build_file = "@com_extension_dev//build:third_party/yaml-cpp.BUILD",
    #commit = "9a3624205e8774953ef18f57067b3426c1c5ada6",
    tag="0.8.0",
    remote = "https://github.com/jbeder/yaml-cpp.git",
)

# new_local_repository(
#     name = "yaml-cpp",
#     build_file = "@//build:third_party/yaml-cpp.BUILD",
#     path = "/usr",
# )

git_repository(
    name = "rules_python",
    remote = "https://github.com/bazelbuild/rules_python.git",
    tag = "0.1.0",  # Use the tag corresponding to version 0.1.0
)

git_repository(
    name = "magic_enum",
    remote = "https://github.com/Neargye/magic_enum.git",
    strip_prefix = "",  # No need for strip_prefix since Git directly clones the repository
    tag = "v0.9.3",  # Use the tag corresponding to version 0.9.3
)

# new_local_repository(
#     name = "cuml",
#     build_file = "@//build:third_party/cuml.BUILD",
#     path = "/usr/local",
# )

new_local_repository(
    name = "glib",
    build_file = "//build:third_party/glib_nobuild.BUILD",
    # path = "/usr/local",
    path = "/usr",
)

new_local_repository(
    name = "opencv_linux",
    build_file = "@//build:third_party/opencv_linux.BUILD",
    path = "/usr/include",
)

# cc_import(
#     name = "glib",
#     hdrs = ["/usr/local/lib/x86_64-linux-gnu/glib-2.0/include/glibconfig.h"],
#     includes = ["/usr/local/include/glib-2.0", "/usr/local/lib/x86_64-linux-gnu/glib-2.0/include"],
#     system_provided = 1,
# )

# new_local_repository(
#     name = "glib_lib",
#     build_file = "@//build:third_party/glib_nobuild.BUILD",
#     path = "/usr/local/lib",
#     # path = "/usr",
# )

# new_git_repository(
#     name = "glib",
#     build_file = "//build:third_party/glib.BUILD",
#     commit = "763cc3b238398614c20069fd67642730e3a6519b",
#     patch_cmds = [
#         "meson setup builddir -Ddebug=true -Dprefix=$(pwd)/external",
#         "ninja -C builddir install",
#     ],
#     remote = "https://github.com/GNOME/glib.git",
# )

new_local_repository(
    name = "json_glib",
    build_file = "@//build:third_party/json_glib.BUILD",
    path = "/usr",
)

new_local_repository(
    name = "gstreamer",
    build_file = "@//build:third_party/gstreamer_nobuild.BUILD",
    # path = "/usr/local",
    path = "/usr",
)

# new_git_repository(
#     name = "gstreamer",
#     build_file = "//build:third_party/gstreamer.BUILD",
#     commit = "2d8273151571fcab887cc81de48e87aeb61b5c06",
#     patch_cmds = [
#         "meson setup builddir -Ddebug=true -Dprefix=$(pwd)/external",
#         "ninja -C builddir install",
#     ],
#     remote = "https://github.com/GStreamer/gstreamer.git",
#     shallow_since = "1712695735 +0100",
# )

new_local_repository(
    name = "libsoup",
    build_file = "@//build:third_party/libsoup.BUILD",
    path = "/usr",
)

