load("@rules_cc//cc:defs.bzl", "cc_binary")

cc_binary(
    name = "dual-record",
    srcs = [
        "dual_record.cpp",
    ],
    copts = [
        "-std=c++17",
        "-Wno-error=write-strings",
    ],
    deps = [
        "@glib",
        "@gstreamer",
    ],
    visibility = ["//visibility:public"],
)

cc_binary(
    name = "dual-recordd",
    srcs = [
        "dual_record_service.cpp",
        "dual_record_service.h",
        "dual-recordd.cpp",
    ],
    copts = ["-std=c++17"],
    deps = [
        "@glib",
        "@gstreamer",
    ],
    visibility = ["//visibility:public"],
)

cc_binary(
    name = "dualctl",
    srcs = [
        "dualctl.cpp",
    ],
    copts = ["-std=c++17"],
    deps = [],
    visibility = ["//visibility:public"],
)

cc_binary(
    name = "gopro_remote_bridge",
    srcs = [
        "gopro_remote_bridge.cpp",
    ],
    copts = [
        "-std=c++17",
        "-DHSTREAM_HAVE_SIMPLEBLE",
        "-I/usr/local/include",
    ],
    linkopts = [
        "-ldbus-1",
        "-l:/usr/local/lib/libsimpleble.a",
        "-l:/usr/local/lib/libsimpledbus.a",
        "-lbluetooth",
        "-lpthread",
        "-ldl",
    ],
    visibility = ["//visibility:public"],
)
