load("@rules_cc//cc:defs.bzl", "cc_binary")

cc_binary(
    name = "dual-record",
    srcs = [
        "dual_record.cpp",
    ],
    copts = [
        "-std=c++17",
        "-Wno-error=write-strings",
    ],
    deps = [
        "@glib",
        "@gstreamer",
    ],
    visibility = ["//visibility:public"],
)

